### ISSUE TITLE
First Capistrano update fails `mkdir: cannot create directory ‘/home/deploy’: Permission denied` Ubuntu 20.04

### ISSUE THREAD

**Issue by 4-3is4-me** [consuldemocracy/installer#236]
Apologies if this is better suited to the main repo, but as the readme here gives instructions for setting up Capsitrano I chose to open the issue here. I have deployed to Ubuntu 20.04 on AWS, to avoid root access I changed the installer `group_vars/all` to
```
deploy_user: ubuntu 
deploy_group: sudo
```
and I updated `deploy-secrets.yml` to `user: "ubuntu"` in the other repo.

On running `cap production deploy --trace` I get the following error:
```
** Invoke production (first_time)
** Execute production
** Invoke load:defaults (first_time)
** Execute load:defaults
** Invoke bundler:map_bins (first_time)
** Execute bundler:map_bins
** Invoke deploy:set_rails_env (first_time)
** Execute deploy:set_rails_env
** Invoke deploy:set_linked_dirs (first_time)
** Execute deploy:set_linked_dirs
** Invoke deploy:set_rails_env
** Invoke rvm1:hook (first_time)
** Execute rvm1:hook
00:00 rvm1:hook
       01 mkdir -p /home/deploy/consul/rvm1scripts/
       01 mkdir: cannot create directory ‘/home/deploy’: Permission denied
#<Thread:0x00007fac5b0c9630 /home/ubuntu/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/sshkit-1.21.5/lib/sshkit/runners/parallel.rb:10 run> terminated with exception (report_on_exception is true):
/home/ubuntu/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/sshkit-1.21.5/lib/sshkit/runners/parallel.rb:15:in `rescue in block (2 levels) in execute': Exception while executing as ubuntu@xxx.xxx.xxx: mkdir exit status: 1 (SSHKit::Runner::ExecuteError)
mkdir stdout: mkdir: cannot create directory ‘/home/deploy’: Permission denied
mkdir stderr: Nothing written
```
I understand it will have worked better with a deploy user configured before running the installer, but the configs do allow for an alternate user to be used. Before I destroy and start again, can I make a change anywhere to use directory `/home/ubuntu` ?

**Comment by javierm** [comment]
Hi, @4-3is4-me :smile:.

Try changing the `deploy_to` line in the `deploy-secrets.yml` file, so its value is `"/home/ubuntu/consul"`.

Hope that works!

**Comment by 4-3is4-me** [comment]
Yes, it worked I hadn't noticed that, thank you. Not sure if it's related, but now I am getting the 404 page. The change I made was to enable multitenancy 
[https://docs.consuldemocracy.org/tech_docs/features/multitenancy#common-step-for-all-consul-democracy-installations](url)
application_custom.rb looks like this
```module Consul
  class Application < Rails::Application
    config.multitenancy = true
  end
end
```
Any guidance you can offer is gratefully received. 😊

**Comment by 4-3is4-me** [comment]
Apologies, I also cannot get multitenancy to be enabled using the other option in
[https://docs.consuldemocracy.org/tech_docs/features/multitenancy#common-step-for-all-consul-democracy-installations](url)
so I will open another issue in the consul repo if I cannot get it to work.
As my original query is resolved I will mark as closed.
Thanks again 😊

**Comment by javierm** [comment]
Hi again, @4-3is4-me :smile:.

Make sure the `server_name` is correctly configured in the `secrets.yml` file (its value should be the domain of your application; for example, in our demo server, we have `server_name: "demo.consuldemocracy.org"`). This is supposed to be configured before running the installer, but unfortunately the documentation isn't clear about that because we also support deploying to IP addresses with no domain :relieved:. Sorry for that! :pray:

If that doesn't solve the issue, could you check the logs and paste the output when you get the 404 error? Also, what's the URL you're accessing?

**Comment by 4-3is4-me** [comment]
@javierm thanks again, that did the trick! I think it's my error as it was configured as the local IP. I am using two ubuntu EC2s in AWS, one as a 'local' machine to configure the other as a server. We are a volunteer group and I want to make it as easy as possible for others to access the 'local' machine to push updates. We aren't using Consul in production at the moment, but we may be offering it as a service to local community councils if it's suitable.  😊
